add document for members to README.md
TEAra-official/teara-website pull request #30
Opened 2022-02-14 13:13 UTC by konamilk09

## Description

| Github URL | https://github.com/TEAra-official/teara-website/issues/14 |

## What
メンバーの追加方法についてのドキュメントのセクションをREADMEに追加

## Why

## Requirements
- [x] セルフレビューをした
- [x] コードにフォーマットをかけた
- [x] 正しいbranchに向かってマージさせようとしている

2022-02-14 14:06 UTC, NamikoToriyama requested changes
100ちゃんと私がpageを作成した後に、ドキュメントみます🙏

2022-04-21 12:35 UTC, NamikoToriyama commented on README.md
> +- アイコンに使う画像を`public/images/members-icon`に入れる。
初心者でもできるように、メンバーの追加方法の前後に、「ブランチをきる」「pull requestを作成する」を書いてください🙏 (できればコマンドとかも)

2022-04-21 12:36 UTC, NamikoToriyama commented on README.md
> +- 間違えると修正がちょっとだけ面倒なので入力する文は事前に考えておく。
修正するときは、どのファイルを修正すればいいかを書いてあげればいいかを書いてあげてください🙏

2022-04-21 14:37 UTC, Hunachi commented on README.md
> +- ブランチを切る。
[IMO]`main`ブランチからというのは暗黙の了解な気もするけど一応入れといたがいいかもと思います！

2022-04-21 14:37 UTC, Hunachi commented on README.md
> +    - `git checkout -b make-konami`とターミナルで打つ。`konami`の部分は自分の名前に変更する。
`git checkout -b make-konami` → `git switch -c make-konami`

2022-04-21 14:37 UTC, Hunachi commented on README.md
> +- pull requestを出す。
[IMO]　プルリクの説明まで入れるなら`add`と`commit`の説明があってもいいかもしれない

2022-04-21 14:37 UTC, Hunachi commented on README.md
> +- pull requestを出す。
どのファイルをコミットに追加するかも書いたがいいかも（私は色々いじってたのもあるけど選別しなきゃいけなかった...）

2022-06-23 03:33 UTC, merged