フォントの決定
TEAra-official/teara-website pull request #48
Opened 2022-02-25 12:32 UTC by si-tm

## Description

| Github URL | https://github.com/TEAra-official/teara-website/issues/21 |

## What
### どのフォントが良いか選んでいただきたいです🙇‍♂️
**日本語フォント**
1. M PLUS Rounded 1c
<img width="800" alt="スクリーンショット 2022-03-07 17 37 50" src="https://user-images.githubusercontent.com/57259352/156996417-e32b2f79-8ae5-4ce9-abcb-909e1a4468fe.png">

2. Shippori Mincho B1
<img width="800" alt="スクリーンショット 2022-03-07 17 38 51" src="https://user-images.githubusercontent.com/57259352/156996590-eff180fd-6faa-4abd-b452-9a01c57f0104.png">

3. Kiwi Maru
<img width="800" alt="スクリーンショット 2022-03-07 17 42 04" src="https://user-images.githubusercontent.com/57259352/156997058-7f90afc5-cdeb-4681-9ca2-9e998e2a70c9.png">

**英語**

1. Times New Roman
<img width="800" alt="スクリーンショット 2022-03-07 17 47 04" src="https://user-images.githubusercontent.com/57259352/156997853-0a374ffa-379c-4dd5-8f4a-4c2c6bd4f2c6.png">

2. Lora
<img width="800" alt="スクリーンショット 2022-03-07 17 48 59" src="https://user-images.githubusercontent.com/57259352/156998145-cdc2d3a9-cef3-4bcc-9d5a-e6e1b1281898.png">

3. Cormorant Garamond
<img width="800" alt="スクリーンショット 2022-03-07 17 50 53" src="https://user-images.githubusercontent.com/57259352/156998418-afcaa39f-038a-4292-b604-34b812bc9671.png">

タイトルのフォントを変更
参考 : [Google Fonts](https://fonts.google.com/), [Google Fontsのスタイルと太さ](https://ja.horecapolis.info/758658-specifying-style-and-weight-for-YFOJBA)
## Why

## Requirements
- [ ] セルフレビューをした
- [ ] コードにフォーマットをかけた
- [ ] 正しいbranchに向かってマージさせようとしている

2022-04-04 13:02 UTC, NamikoToriyama commented on style/about.css
> +  /* font-family: "游ゴシック"; */
これ消してほしい

2022-04-04 13:02 UTC, NamikoToriyama commented on pages/header.jsx
> +              <Nav.Link className={"header-text" + " " + "plain-text-english"}>
これでいけるような気がする
```suggestion
              <Nav.Link className="header-text plain-text-english">
```

2022-04-04 13:03 UTC, NamikoToriyama commented on pages/components/page-title.jsx
> +      <h1 className={"page-title" + "title"}>{props.title}</h1>
```suggestion
      <h1 className="page-title title">{props.title}</h1>

```

2022-04-04 13:03 UTC, NamikoToriyama commented on pages/components/members/members.jsx
> +      <h2 id="members" className={"about-title" + " " + "title"}>MEMBERS</h2>
```suggestion
      <h2 id="members" className="about-title title">MEMBERS</h2>
```

2022-04-04 13:03 UTC, NamikoToriyama commented on pages/components/members/members.jsx
> +    <div className={"members-content" + " " + "plain-text-japanese"}>
```suggestion
    <div className="members-content plain-text-japanese">
```

2022-04-04 13:04 UTC, NamikoToriyama commented on pages/components/contact.jsx
> +      <h2 id="contact" className={"contact-title" + " " + "title"}>CONTACT</h2>
```suggestion
    <div className="contact-content plain-text-japanese">
      <h2 id="contact" className="contact-title title">CONTACT</h2>
```

2022-04-04 13:04 UTC, NamikoToriyama commented on pages/components/add_activities.jsx
> +
ここのスペース消してほしい

2022-04-04 13:04 UTC, NamikoToriyama commented on pages/components/add_activities.jsx
> +
ここも消してほしい

2022-04-04 13:04 UTC, NamikoToriyama commented on pages/components/activities.jsx
> +                 <h2 id="activities" className={"title"}>ACTIVITIES</h2>
{}はいらない
```suggestion
                 <h2 id="activities" className="title">ACTIVITIES</h2>
```

2022-04-04 13:05 UTC, NamikoToriyama commented on style/about.css
> +  /* font-family: "Times New Roman"; */
ここのコメントアウト消してほしい

2022-04-04 13:05 UTC, NamikoToriyama requested changes

2022-04-04 13:05 UTC, NamikoToriyama commented on style/index.css
> +}
これって他の部分にも影響でていませんか？？？不安

2022-04-04 13:12 UTC, si-tm commented on pages/components/add_activities.jsx
> +
私の手元で9行目に`</ul>`が来てるので、あとでコミットしたものを確認してくださると嬉しいです🙇‍♂️

2022-04-04 13:16 UTC, si-tm commented on style/index.css
> +}
別のpull requestで修正した箇所で、pullし忘れてしまいました。

2022-04-04 13:28 UTC, NamikoToriyama commented on pages/components/activities.jsx
> +            <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700&display=swap" rel="stylesheet"/>
ここ

2022-04-04 13:28 UTC, NamikoToriyama commented on pages/components/activities.jsx
> +                  <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@400;500&family=M+PLUS+Rounded+1c&family=Reggae+One&family=Roboto+Serif:ital,wght@0,500;0,700;1,600&display=swap"
ここ

2022-04-04 13:29 UTC, NamikoToriyama commented on style/index.css
> +  font-family: 'M PLUS Rounded 1c', sans-serif;
ここ

2022-04-04 13:29 UTC, NamikoToriyama commented on style/index.css
> +  font-family: 'Cormorant Garamond', serif;
ここ

2022-04-04 13:29 UTC, NamikoToriyama commented on style/index.css
> +  font-family: 'Cormorant Garamond', serif;
titleもついてる

2022-04-04 13:47 UTC, si-tm commented on pages/components/activities.jsx
> +            <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700&display=swap" rel="stylesheet"/>
この行の有る無しでACTIVITIESだけじゃなくて他のタイトルのフォントも変わりました。
理由がわからないのですが、このままでも良いでしょうか...？
<img width="772" alt="スクリーンショット 2022-04-04 22 45 58" src="https://user-images.githubusercontent.com/57259352/161557992-bb7ac7c4-f314-4cb4-bb3d-fe9e5ce5c384.png">
<img width="772" alt="スクリーンショット 2022-04-04 22 46 08" src="https://user-images.githubusercontent.com/57259352/161558008-3cbaa379-27d2-490b-9158-fdd173090ff7.png">

2022-04-04 13:58 UTC, si-tm commented on pages/components/activities.jsx
> +                  <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@400;500&family=M+PLUS+Rounded+1c&family=Reggae+One&family=Roboto+Serif:ital,wght@0,500;0,700;1,600&display=swap"
こちらも有る無しで全体のフォントが変化しました。
**有る**
<img width="772" alt="スクリーンショット 2022-04-04 22 57 05" src="https://user-images.githubusercontent.com/57259352/161560065-be531974-e6b2-4765-b21e-8d48fe230ca1.png">

**無し** 
<img width="772" alt="スクリーンショット 2022-04-04 22 57 12" src="https://user-images.githubusercontent.com/57259352/161560110-2d594d2a-2434-4185-9a1b-31a51030b355.png">

2022-04-04 15:16 UTC, NamikoToriyama requested changes
フォントの定義が4,5ヶ所されていて、どれが適用したいフォントなのかがわからならないです。以下が見る限りのフォントなのですが、どれが意図しているフォントですか？

関係ないのは消すなり、CSSつけるなりして欲しいです。

```
.plain-text-japanese
  font-family: 'M PLUS Rounded 1c', sans-serif; 


.plain-text-english
 font-family: 'Cormorant Garamond', serif;


.title
  font-family: 'Cormorant Garamond', serif;

.plain-text
  font-family: 'Roboto Mono', monospace;

ACTIVITIES
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700&display=swap" rel="stylesheet"/>

ACTIVITIESの中身 (コメントアウト前)
<link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@400;500&family=M+PLUS+Rounded+1c&family=Reggae+One&family=Roboto+Serif:ital,wght@0,500;0,700;1,600&display=swap" rel="stylesheet"></link>
```

2022-04-14 12:34 UTC, NamikoToriyama approved these changes

2022-04-14 12:34 UTC, merged